### ISSUE TITLE
in ubuntu18.04 ,after change the trt path in cmakelist,  then make, it has error

### ISSUE THREAD

**Issue by henbucuoshanghai** [wdhao/tensorrtCV#2]
home//tensorrtCV/calibrator.cpp:125:61: error: expected primary-expression before ‘char’
         copy(istream_iterator<char>(input),istream_iterator<char>(),back_inserter(m_CalibrationCache));
                                                             ^~~~
CMakeFiles/tensorrtF.dir/build.make:108: recipe for target 'CMakeFiles/tensorrtF.dir/calibrator.cpp.o' failed
make[2]: *** [CMakeFiles/tensorrtF.dir/calibrator.cpp.o] Error 1
CMakeFiles/Makefile2:95: recipe for target 'CMakeFiles/tensorrtF.dir/all' failed
make[1]: *** [CMakeFiles/tensorrtF.dir/all] Error 2
Makefile:103: recipe for target 'all' failed
make: *** [all] Error 2

tks

**Comment by BaofengZan** [comment]
已经修改，文件为： calibrator.cpp。可以手动对比修改下，就添加一个头文件

**Comment by henbucuoshanghai** [comment]
/tensorrtCV/trt.h:6:10: fatal error: json.h: No such file or directory
 #include <json.h>
          ^~~~~~~~
compilation terminated.
CMakeFiles/tensorrtF.dir/build.make:147: recipe for target 'CMakeFiles/tensorrtF.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/tensorrtF.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:95: recipe for target 'CMakeFiles/tensorrtF.dir/all' failed
make[1]: *** [CMakeFiles/tensorrtF.dir/all] Error 2
Makefile:103: recipe for target 'all' failed
make: *** [all] Error 2
问题解决了  但是遇到新的问题  make的时候

**Comment by BaofengZan** [comment]
再更新下 trt.h

**Comment by henbucuoshanghai** [comment]
热心的帮助  最后一次 tks
生成tensorrtf之后   路径修改后 运行
./tensorrtF -e ../model/resnet50.json  imgs
res50是官方的  wts生成了 但是遇到下面error   tks

This networt's layer number is : 0
Building the Engine...
ERROR: Network must have at least one output
ERROR: Network validation failed.
tensorrtF: tensorrtCV/trt.cpp:142: void trt::createENG(): Assertion `engine != nullptr' failed.
Aborted (core dumped)

**Comment by henbucuoshanghai** [comment]
你好   main.cpp里面的 我修改了很多   test() 和 resnet() 均运行不了  我大修后  仍然失败  
永远This networt's layer number is : 0
读取json总是有问题     求助    m_trt->createENG();

**Comment by henbucuoshanghai** [comment]
跑通了main.cpp里面的test   输出的前56个元素是nan？        请问对吗？
NKNOWN: Deserialize required 224690 microseconds.
WARNING: TensorRT was linked against cuDNN 8.0.5 but loaded cuDNN 8.0.4
UNKNOWN: Allocated persistent device memory of size 47219200
UNKNOWN: Allocated activation device memory of size 55050240
UNKNOWN: Assigning persistent memory blocks for various profiles
nan nan nan nan nan nan nan nan 
nan nan nan nan nan nan nan nan 
nan nan nan nan nan nan nan nan 
nan nan nan nan nan nan nan nan 
nan nan nan nan nan nan nan nan 
nan nan nan nan nan nan nan nan 
nan nan nan nan nan nan nan nan

**Comment by henbucuoshanghai** [comment]
最后一些问题，多谢解答。
按照onnx的可视化   一层层的写json吗？  请问写起来快吗？比如yolo5需要多久写好json？
生成engine推理后，用trt::doInference得到结果，但是后处理什么的依旧自己写？

**Comment by henbucuoshanghai** [comment]
-e  -d这一块代码需要加一点吧   trt.cpp里面好像需要对应的修改？

**Comment by pgdtgq** [comment]
> 最后一些问题，多谢解答。
> 按照onnx的可视化一层层的写JSON吗？请问写起来快吗？比如yolo5需要多久写好的json？
> 生成引擎推理后，用TRT :: doInference得到结果，但是后处理什么的过去自己写的？

速度很快的，一般2天左右写完。后处理自己写，你可以参考别的开源代码，都有的。

**Comment by pgdtgq** [comment]
> 最后一些问题，多谢解答。
> 按照onnx的可视化一层层的写JSON吗？请问写起来快吗？比如yolo5需要多久写好的json？
> 生成引擎推理后，用TRT :: doInference得到结果，但是后处理什么的过去自己写的？

速度很快的，写好一般两天左右，后处理可以参考别的开源代码写。

**Comment by pgdtgq** [comment]
一层层写根据这个框架很快的，一般两天左右，后处理可以参考开源的代码写。

**Comment by pgdtgq** [comment]
> ，

写起来很快，一般两天左右。后处理参考开源代码。

**Comment by henbucuoshanghai** [comment]
跑通了main.cpp里面的test 输出的前56个元素是nan？ 请问对吗？
NKNOWN: Deserialize required 224690 microseconds.
WARNING: TensorRT was linked against cuDNN 8.0.5 but loaded cuDNN 8.0.4
UNKNOWN: Allocated persistent device memory of size 47219200
UNKNOWN: Allocated activation device memory of size 55050240
UNKNOWN: Assigning persistent memory blocks for various profiles
nan nan nan nan nan nan nan nan
nan nan nan nan nan nan nan nan

**Comment by henbucuoshanghai** [comment]
reduce模块是什么意思呢    降低什么？不是很懂？
