### ISSUE TITLE
reduce模块意思不是很懂  求解释

### ISSUE THREAD

**Issue by henbucuoshanghai** [wdhao/tensorrtCV#4]

**Comment by henbucuoshanghai** [comment]
UNKNOWN: Deserialize required 523706 microseconds.
WARNING: TensorRT was linked against cuDNN 8.0.5 but loaded cuDNN 8.0.4
UNKNOWN: Allocated persistent device memory of size 109056
UNKNOWN: Allocated activation device memory of size 236544
UNKNOWN: Assigning persistent memory blocks for various profiles

请问意思是什么呢？占用显存236544？  可以自己设置2G？

**Comment by wdhao** [comment]
这个是生成eng文件过程种需要的显存大小，这个和maxWorkSize是不一样的

**Comment by henbucuoshanghai** [comment]
请问文档里的第15个api  是reduce  请问什么作用呢 为什么里面有pool，和池化才api有什么区别吗？
15）reduce:
      "layerStyle": "reduce",
      "layerName": "avgPool",
      "inputName": "resnet4_2",
"dtype": "kMAX",      reduce的类型，默认是kAVG
      "keepD": true,       是否保存和输入相同的维度，如果设置false，则当做完reduce操作后，如果有维度等于1，则删除这个维度，例如:[256,20,1]--->[256,20]
      "axes": 6           在指定的维度上做reduce操作

**Comment by wdhao** [comment]
这里的的pool操作是用reduce做了个变换而已，当然也可以用pooling操作。至于reduce的用法，是指沿着指定的维度做指定类型的操作，例如：max/avg等等

**Comment by henbucuoshanghai** [comment]
你好  maxWorkSize是什么意思呢？1<<30是什么意思呢？多谢多谢

**Comment by wdhao** [comment]
maxWorkSize是指最大的工作显存，如果超出这个会提示out of memory。
1<<30是指1GB的大小
