### ISSUE TITLE
通过getWeights.py 解析出的yolov3-tiny权重没有wts\\{anchor_grid}.wgt  文件

### ISSUE THREAD

**Issue by SixGodGG** [wdhao/tensorrtCV#6]
通过getWeights.py 解析出的yolov3-tiny权重没有wts\\{anchor_grid}.wgt  文件  需要自己手动添加上吗？

**Comment by SixGodGG** [comment]
anchor_grid  这个变量是自己要写到模型权重中的吗？

**Comment by wdhao** [comment]
如果没有解析到这个anchor信息的话，可以在代码里面改动一下，直接把anchor传递进去，不用读这个anchor_gird文件了

**Comment by SixGodGG** [comment]
好的，我现在就是这样弄的，我在你的基础上写了一个yolov3-tiny的json，但是代码部分yolo的一些内容进行了修（白）改（嫖），按照wxy的。 可以pr吗，yolo部分因为你还没有讲，也没有公开的json，我按照我自己思路写的，有需要的朋友可进行参考对照。
