### ISSUE TITLE
多个输出怎么修改呢？

### ISSUE THREAD

**Issue by henbucuoshanghai** [wdhao/tensorrtCV#7]
cudaMemcpyAsync(output,m_bindings.at(outputIndex),batchsize * param.outputSize * 4, cudaMemcpyDeviceToHost,m_cudaStream)

**Comment by wdhao** [comment]
目前没有写多输出的代码，不过，多输出可以先调用shuffle，拉伸成一个维度，然后concat起来。

**Comment by henbucuoshanghai** [comment]
自己加一层 把输出的所有层  先flatten 拼接 然后输出？   得到结果然后按顺序截断，各自reshape回去？

**Comment by wdhao** [comment]
你单个输出的时候就是float*的类型，已经没有shape了，多个输出也一样，不过是后面截断罢了
