### ISSUE TITLE
加强版本什么时候出呢？比如：可视化？多输出？前后处理？

### ISSUE THREAD

**Issue by henbucuoshanghai** [wdhao/tensorrtCV#9]
二三个月？

**Comment by pgdtgq** [comment]
陆续更新，前处理的最近会出一版。

**Comment by henbucuoshanghai** [comment]
PReLU  怎样实现呢？

**Comment by henbucuoshanghai** [comment]
多谢多谢

**Comment by wdhao** [comment]
PReLU这里已经实现了，可以看下trt_prelu函数的写法

**Comment by henbucuoshanghai** [comment]
找到了  文档和项目代码 有些出入。。  还是自己研究。。  热心的回复

**Comment by henbucuoshanghai** [comment]
你好 找到prelu  但是onnx模型里，点击这一层  没有对应的权重  请问怎么回事？[
![Uploading Screenshot from 2021-06-16 14-38-48.png…]()

**Comment by wdhao** [comment]
onnx里面没有是没关系的，只要解析pt的时候能生成这个文件就行

**Comment by henbucuoshanghai** [comment]
那json里面怎么写呢？权重地址？自己从wts文件夹里找吗?那名字是什么呢？多谢多谢

**Comment by wdhao** [comment]
prelu是有权重的，你可以对照着onnx去找一下，要么就print一下整个model，然后看一下

**Comment by wdhao** [comment]
每个网络里面的命名是不一样的，我也不清楚你的网络里面是怎么样的命名方式

**Comment by henbucuoshanghai** [comment]
多谢热心的回复  
最后一个问题，如果模型里有自定义的函数，请问怎么实现？比如1/(2+e^x)+2  请问此时怎样实现？  x是某特征图

**Comment by henbucuoshanghai** [comment]
Conv_118 parameters : 256,3,3,1,1,1,1 dilations: 1,1,groups = 1
Conv_118 dims :  : 256 64 128 
Segmentation fault (core dumped)

运行到某一层 突然报错  如上   请问怎样解决？是哪里出问题？tks

**Comment by wdhao** [comment]
这种段错误不好确定，需要到代码里面调试，你可以先自己调试一下

**Comment by henbucuoshanghai** [comment]
你好 设置setMaxWorkspaceSize的数值  20  30 28   但是生成的模型   测试下来 性能基本不变  请问怎么回事呢？

**Comment by wdhao** [comment]
这个是指申请最大的工作空间而已，超过模型占用的显存即可，和模型的性能无关

**Comment by henbucuoshanghai** [comment]
不是很懂  那比如yolo5  设置1<<20   内存不够吧  太小了吧。。会怎么影响呢？

**Comment by henbucuoshanghai** [comment]
比如怎样让模型运行的时候  显存自己规定占几个g？  可以认为规定？

**Comment by henbucuoshanghai** [comment]
人为设定？

**Comment by wdhao** [comment]
推理阶段的最大显存是由很多因素决定的，batchsize，imgsize，eng反序列化等等
生成模型的workplace是由最大权重和batchsize决定的，你没必要纠结这个东西。

**Comment by henbucuoshanghai** [comment]
多谢   那  他在边缘盒子 或芯片  上运行时    所占的显存是芯片本身的问题？无法人为？
